name: Release build

on:
  push:
    branches:
      - release/**

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Update project version
        run: |
          mvn versions:set -DnewVersion=${GITHUB_REF##*/}-rc -DgenerateBackupPoms=false
          git config --global user.name 'GitHub action'
          git config --global user.mail 'github-action@noreply.github.com'
          git add .
          git commit -m 'Create snapshot [ci skip]'
          git push